/*
 * Copyright (C) 2010 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sky.parallaxeffect;

public class Cheeses {

    public static final String[] LETTERS = new String[]{"#", "A", "B", "C", "D",
            "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q",
            "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};


    public static final String QQ_FUCTIONS[] = {"开通会员", "QQ钱包", "个性装扮", "我的收藏", "我的相册", "我的文件", "我的名片夹", "登出"};

    public static final String[] CHEESE_STRINGS = {
            "Abbaye de Belloc", "Abbaye du Mont des Cats", "Abertam", "Abondance", "Ackawi",
            "Acorn", "Adelost", "Affidelice au Chablis", "Afuega'l Pitu", "Airag", "Airedale",
            "Aisy Cendre", "Allgauer Emmentaler", "Alverca", "Ambert", "American Cheese",
            "Ami du Chambertin", "Anejo Enchilado", "Anneau du Vic-Bilh", "Anthoriro", "Appenzell",
            "Aragon", "Ardi Gasna", "Ardrahan", "Armenian String", "Aromes au Gene de Marc",
            "Asadero", "Asiago", "Aubisque Pyrenees", "Autun", "Avaxtskyr", "Baby Swiss",
            "Babybel", "Baguette Laonnaise", "Bakers", "Baladi", "Balaton", "Bandal", "Banon",
            "Barry's Bay Cheddar", "Basing", "Basket Cheese", "Bath Cheese", "Bavarian Bergkase",
            "Baylough", "Beaufort", "Beauvoorde", "Beenleigh Blue", "Beer Cheese", "Bel Paese",
            "Bergader", "Bergere Bleue", "Berkswell", "Beyaz Peynir", "Bierkase", "Bishop Kennedy",
            "Blarney", "Bleu d'Auvergne", "Bleu de Gex", "Bleu de Laqueuille",
            "Bleu de Septmoncel", "Bleu Des Causses", "Blue", "Blue Castello", "Blue Rathgore",
            "Blue Vein (Australian)", "Blue Vein Cheeses", "Bocconcini", "Bocconcini (Australian)",
            "Boeren Leidenkaas", "Bonchester", "Bosworth", "Bougon", "Boule Du Roves",
            "Boulette d'Avesnes", "Boursault", "Boursin", "Bouyssou", "Bra", "Braudostur",
            "Breakfast Cheese", "Brebis du Lavort", "Brebis du Lochois", "Brebis du Puyfaucon",
            "Bresse Bleu", "Brick", "Brie", "Brie de Meaux", "Brie de Melun", "Brillat-Savarin",
            "Brin", "Brin d' Amour", "Brin d'Amour", "Brinza (Burduf Brinza)",
            "Briquette de Brebis", "Briquette du Forez", "Broccio", "Broccio Demi-Affine",
            "Brousse du Rove", "Bruder Basil", "Brusselae Kaas (Fromage de Bruxelles)", "Bryndza",
            "Buchette d'Anjou", "Buffalo", "Burgos", "Butte", "Butterkase", "Button (Innes)",
            "Buxton Blue", "Cabecou", "Caboc", "Cabrales", "Cachaille", "Caciocavallo", "Caciotta",
            "Caerphilly", "Cairnsmore", "Calenzana", "Cambazola", "Camembert de Normandie",
            "Canadian Cheddar", "Canestrato", "Cantal", "Caprice des Dieux", "Capricorn Goat",
            "Capriole Banon", "Carre de l'Est", "Casciotta di Urbino", "Cashel Blue", "Castellano",
            "Castelleno", "Castelmagno", "Castelo Branco", "Castigliano", "Cathelain",
            "Celtic Promise", "Cendre d'Olivet", "Cerney", "Chabichou", "Chabichou du Poitou",
            "Chabis de Gatine", "Chaource", "Charolais", "Chaumes", "Cheddar",
            "Cheddar Clothbound", "Cheshire", "Chevres", "Chevrotin des Aravis", "Chontaleno",
            "Civray", "Coeur de Camembert au Calvados", "Coeur de Chevre", "Colby", "Cold Pack",
            "Comte", "Coolea", "Cooleney", "Coquetdale", "Corleggy", "Cornish Pepper",
            "Cotherstone", "Cotija", "Cottage Cheese", "Cottage Cheese (Australian)",
            "Cougar Gold", "Coulommiers", "Coverdale", "Crayeux de Roncq", "Cream Cheese",
            "Cream Havarti", "Crema Agria", "Crema Mexicana", "Creme Fraiche", "Crescenza",
            "Croghan", "Crottin de Chavignol", "Crottin du Chavignol", "Crowdie", "Crowley",
            "Cuajada", "Curd", "Cure Nantais", "Curworthy", "Cwmtawe Pecorino",
            "Cypress Grove Chevre", "Danablu (Danish Blue)", "Danbo", "Danish Fontina",
            "Daralagjazsky", "Dauphin", "Delice des Fiouves", "Denhany Dorset Drum", "Derby",
            "Dessertnyj Belyj", "Devon Blue", "Devon Garland", "Dolcelatte", "Doolin",
            "Doppelrhamstufel", "Dorset Blue Vinney", "Double Gloucester", "Double Worcester",
            "Dreux a la Feuille", "Dry Jack", "Duddleswell", "Dunbarra", "Dunlop", "Dunsyre Blue",
            "Duroblando", "Durrus", "Dutch Mimolette (Commissiekaas)", "Edam", "Edelpilz",
            "Emental Grand Cru", "Emlett", "Emmental", "Epoisses de Bourgogne", "Esbareich",
            "Esrom", "Etorki", "Evansdale Farmhouse Brie", "Evora De L'Alentejo", "Exmoor Blue",
            "Explorateur", "Feta", "Feta (Australian)", "Figue", "Filetta", "Fin-de-Siecle",
            "Finlandia Swiss", "Finn", "Fiore Sardo", "Fleur du Maquis", "Flor de Guia",
            "Flower Marie", "Folded", "Folded cheese with mint", "Fondant de Brebis",
            "Fontainebleau", "Fontal", "Fontina Val d'Aosta", "Formaggio di capra", "Fougerus",
            "Four Herb Gouda", "Fourme d' Ambert", "Fourme de Haute Loire", "Fourme de Montbrison",
            "Fresh Jack", "Fresh Mozzarella", "Fresh Ricotta", "Fresh Truffles", "Fribourgeois",
            "Friesekaas", "Friesian", "Friesla", "Frinault", "Fromage a Raclette", "Fromage Corse",
            "Fromage de Montagne de Savoie", "Fromage Frais", "Fruit Cream Cheese",
            "Frying Cheese", "Fynbo", "Gabriel", "Galette du Paludier", "Galette Lyonnaise",
            "Galloway Goat's Milk Gems", "Gammelost", "Gaperon a l'Ail", "Garrotxa", "Gastanberra",
            "Geitost", "Gippsland Blue", "Gjetost", "Gloucester", "Golden Cross", "Gorgonzola",
            "Gornyaltajski", "Gospel Green", "Gouda", "Goutu", "Gowrie", "Grabetto", "Graddost",
            "Grafton Village Cheddar", "Grana", "Grana Padano", "Grand Vatel",
            "Grataron d' Areches", "Gratte-Paille", "Graviera", "Greuilh", "Greve",
            "Gris de Lille", "Gruyere", "Gubbeen", "Guerbigny", "Halloumi",
            "Halloumy (Australian)", "Haloumi-Style Cheese", "Harbourne Blue", "Havarti",
            "Heidi Gruyere", "Hereford Hop", "Herrgardsost", "Herriot Farmhouse", "Herve",
            "Hipi Iti", "Hubbardston Blue Cow", "Hushallsost", "Iberico", "Idaho Goatster",
            "Idiazabal", "Il Boschetto al Tartufo", "Ile d'Yeu", "Isle of Mull", "Jarlsberg",
            "Jermi Tortes", "Jibneh Arabieh", "Jindi Brie", "Jubilee Blue", "Juustoleipa",
            "Kadchgall", "Kaseri", "Kashta", "Kefalotyri", "Kenafa", "Kernhem", "Kervella Affine",
            "Kikorangi", "King Island Cape Wickham Brie", "King River Gold", "Klosterkaese",
            "Knockalara", "Kugelkase", "L'Aveyronnais", "L'Ecir de l'Aubrac", "La Taupiniere",
            "La Vache Qui Rit", "Laguiole", "Lairobell", "Lajta", "Lanark Blue", "Lancashire",
            "Langres", "Lappi", "Laruns", "Lavistown", "Le Brin", "Le Fium Orbo", "Le Lacandou",
            "Le Roule", "Leafield", "Lebbene", "Leerdammer", "Leicester", "Leyden", "Limburger",
            "Lincolnshire Poacher", "Lingot Saint Bousquet d'Orb", "Liptauer", "Little Rydings",
            "Livarot", "Llanboidy", "Llanglofan Farmhouse", "Loch Arthur Farmhouse",
            "Loddiswell Avondale", "Longhorn", "Lou Palou", "Lou Pevre", "Lyonnais", "Maasdam",
            "Macconais", "Mahoe Aged Gouda", "Mahon", "Malvern", "Mamirolle", "Manchego",
            "Manouri", "Manur", "Marble Cheddar", "Marbled Cheeses", "Maredsous", "Margotin",
            "Maribo", "Maroilles", "Mascares", "Mascarpone", "Mascarpone (Australian)",
            "Mascarpone Torta", "Matocq", "Maytag Blue", "Meira", "Menallack Farmhouse",
            "Menonita", "Meredith Blue", "Mesost", "Metton (Cancoillotte)", "Meyer Vintage Gouda",
            "Mihalic Peynir", "Milleens", "Mimolette", "Mine-Gabhar", "Mini Baby Bells", "Mixte",
            "Molbo", "Monastery Cheeses", "Mondseer", "Mont D'or Lyonnais", "Montasio",
            "Monterey Jack", "Monterey Jack Dry", "Morbier", "Morbier Cru de Montagne",
            "Mothais a la Feuille", "Mozzarella", "Mozzarella (Australian)",
            "Mozzarella di Bufala", "Mozzarella Fresh, in water", "Mozzarella Rolls", "Munster",
            "Murol", "Mycella", "Myzithra", "Naboulsi", "Nantais", "Neufchatel",
            "Neufchatel (Australian)", "Niolo", "Nokkelost", "Northumberland", "Oaxaca",
            "Olde York", "Olivet au Foin", "Olivet Bleu", "Olivet Cendre",
            "Orkney Extra Mature Cheddar", "Orla", "Oschtjepka", "Ossau Fermier", "Ossau-Iraty",
            "Oszczypek", "Oxford Blue", "P'tit Berrichon", "Palet de Babligny", "Paneer", "Panela",
            "Pannerone", "Pant ys Gawn", "Parmesan (Parmigiano)", "Parmigiano Reggiano",
            "Pas de l'Escalette", "Passendale", "Pasteurized Processed", "Pate de Fromage",
            "Patefine Fort", "Pave d'Affinois", "Pave d'Auge", "Pave de Chirac", "Pave du Berry",
            "Pecorino", "Pecorino in Walnut Leaves", "Pecorino Romano", "Peekskill Pyramid",
            "Pelardon des Cevennes", "Pelardon des Corbieres", "Penamellera", "Penbryn",
            "Pencarreg", "Perail de Brebis", "Petit Morin", "Petit Pardou", "Petit-Suisse",
            "Picodon de Chevre", "Picos de Europa", "Piora", "Pithtviers au Foin",
            "Plateau de Herve", "Plymouth Cheese", "Podhalanski", "Poivre d'Ane", "Polkolbin",
            "Pont l'Eveque", "Port Nicholson", "Port-Salut", "Postel", "Pouligny-Saint-Pierre",
            "Pourly", "Prastost", "Pressato", "Prince-Jean", "Processed Cheddar", "Provolone",
            "Provolone (Australian)", "Pyengana Cheddar", "Pyramide", "Quark",
            "Quark (Australian)", "Quartirolo Lombardo", "Quatre-Vents", "Quercy Petit",
            "Queso Blanco", "Queso Blanco con Frutas --Pina y Mango", "Queso de Murcia",
            "Queso del Montsec", "Queso del Tietar", "Queso Fresco", "Queso Fresco (Adobera)",
            "Queso Iberico", "Queso Jalapeno", "Queso Majorero", "Queso Media Luna",
            "Queso Para Frier", "Queso Quesadilla", "Rabacal", "Raclette", "Ragusano", "Raschera",
            "Reblochon", "Red Leicester", "Regal de la Dombes", "Reggianito", "Remedou",
            "Requeson", "Richelieu", "Ricotta", "Ricotta (Australian)", "Ricotta Salata", "Ridder",
            "Rigotte", "Rocamadour", "Rollot", "Romano", "Romans Part Dieu", "Roncal", "Roquefort",
            "Roule", "Rouleau De Beaulieu", "Royalp Tilsit", "Rubens", "Rustinu", "Saaland Pfarr",
            "Saanenkaese", "Saga", "Sage Derby", "Sainte Maure", "Saint-Marcellin",
            "Saint-Nectaire", "Saint-Paulin", "Salers", "Samso", "San Simon", "Sancerre",
            "Sap Sago", "Sardo", "Sardo Egyptian", "Sbrinz", "Scamorza", "Schabzieger", "Schloss",
            "Selles sur Cher", "Selva", "Serat", "Seriously Strong Cheddar", "Serra da Estrela",
            "Sharpam", "Shelburne Cheddar", "Shropshire Blue", "Siraz", "Sirene", "Smoked Gouda",
            "Somerset Brie", "Sonoma Jack", "Sottocenare al Tartufo", "Soumaintrain",
            "Sourire Lozerien", "Spenwood", "Sraffordshire Organic", "St. Agur Blue Cheese",
            "Stilton", "Stinking Bishop", "String", "Sussex Slipcote", "Sveciaost", "Swaledale",
            "Sweet Style Swiss", "Swiss", "Syrian (Armenian String)", "Tala", "Taleggio", "Tamie",
            "Tasmania Highland Chevre Log", "Taupiniere", "Teifi", "Telemea", "Testouri",
            "Tete de Moine", "Tetilla", "Texas Goat Cheese", "Tibet", "Tillamook Cheddar",
            "Tilsit", "Timboon Brie", "Toma", "Tomme Brulee", "Tomme d'Abondance",
            "Tomme de Chevre", "Tomme de Romans", "Tomme de Savoie", "Tomme des Chouans", "Tommes",
            "Torta del Casar", "Toscanello", "Touree de L'Aubier", "Tourmalet",
            "Trappe (Veritable)", "Trois Cornes De Vendee", "Tronchon", "Trou du Cru", "Truffe",
            "Tupi", "Turunmaa", "Tymsboro", "Tyn Grug", "Tyning", "Ubriaco", "Ulloa",
            "Vacherin-Fribourgeois", "Valencay", "Vasterbottenost", "Venaco", "Vendomois",
            "Vieux Corse", "Vignotte", "Vulscombe", "Waimata Farmhouse Blue",
            "Washed Rind Cheese (Australian)", "Waterloo", "Weichkaese", "Wellington",
            "Wensleydale", "White Stilton", "Whitestone Farmhouse", "Wigmore", "Woodside Cabecou",
            "Xanadu", "Xynotyro", "Yarg Cornish", "Yarra Valley Pyramid", "Yorkshire Blue",
            "Zamorano", "Zanetti Grana Padano", "Zanetti Parmigiano Reggiano"
    };

    public static final int[] ICONS = new int[]{
            R.drawable.pic1, R.drawable.pic2, R.drawable.pic3,R.drawable.pic4,R.drawable.pic5,
            R.drawable.pic6,R.drawable.pic7,R.drawable.pic8,R.drawable.pic9,R.drawable.pic10,
            R.drawable.pic11,R.drawable.pic12,R.drawable.pic13,R.drawable.pic14,R.drawable.pic15
    };

    public static final String[] NAMES = new String[]{"%qwer@", "68*#", "宋江", "卢俊义", "吴用",
            "公孙胜", "关胜", "林冲", "秦明", "呼延灼", "花荣", "柴进", "李应", "朱仝", "鲁智深",
            "武松", "董平", "张清", "杨志", "徐宁", "索超", "戴宗", "刘唐", "李逵", "史进", "穆弘",
            "雷横", "李俊", "阮小二", "张横", "阮小五", " 张顺", "阮小七", "杨雄", "石秀", "解珍",
            " 解宝", "燕青", "朱武", "黄信", "孙立", "宣赞", "郝思文", "韩滔", "彭玘", "单廷珪",
            "魏定国", "萧让", "裴宣", "欧鹏", "邓飞", " 燕顺", "杨林", "凌振", "蒋敬", "吕方",
            "郭 盛", "安道全", "皇甫端", "王英", "扈三娘", "鲍旭", "樊瑞", "孔明", "孔亮", "项充",
            "李衮", "金大坚", "马麟", "童威", "童猛", "孟康", "侯健", "陈达", "杨春", "郑天寿",
            "陶宗旺", "宋清", "乐和", "龚旺", "丁得孙", "穆春", "曹正", "宋万", "杜迁", "薛永", "施恩",
            "周通", "李忠", "杜兴", "汤隆", "邹渊", "邹润", "朱富", "朱贵", "蔡福", "蔡庆", "李立",
            "李云", "焦挺", "石勇", "孙新", "顾大嫂", "张青", "孙二娘", " 王定六", "郁保四", "白胜",
            "时迁", "段景柱"};

    public static final String[] DESCS = new String[]{
            "特殊字符", "特殊字符",
            "天魁星呼保义(及时雨)－宋 江，仗义疏财 怒杀阎婆惜 三打祝家庄、私放晁天王、夜看小鳌山、会神行太保、智取无为军、闹西岳华山...",
            "天罡星 玉麒麟－卢俊义，做事事谨慎，非理不为，非财不取、活捉史文恭、大战玉田县、兵陷青石峪、赚城黑夜、分兵宣州道... ",
            "天机星 智多星－吴用 足智多谋，善用计策，智取生辰纲，说三阮撞等、双掌连环计、使时迁盗甲、转金陵吊挂、智赚卢俊义、智取大名府、智取文安县、计鸩邬梨",
            "天闲星 入云龙－公孙胜 法力高超，建立奇功伟业，应七星聚义、斗法破高廉、芒砀山降魔、兵围百谷岭",
            "天勇星大 刀－关 胜，精通兵法，英勇善战 、议取梁山泊、降水火二将、义降三将",
            "天雄星 豹子头－林 冲，武艺高强，有勇有谋 误入白虎堂...",
            "天猛星 霹雳火－秦 明，武艺高强，性格急躁，有勇无谋，夜走瓦砾场",
            "天威星 双 鞭－呼延灼，正直勇敢、摆布连环马、月夜赚关胜、力擒番将",
            "天英星 小李广－花 荣，箭法高超，十分仗义，大闹清风寨、梁山射雁",
            "天贵星 小旋风－柴 进，为人慷慨，门招天下客、失陷高唐州、簪花入禁苑、藏炮击贼",
            "天富星 扑天雕－李 应，擅长飞刀，神出鬼没，双休生死书",
            "天满星 美髯公－朱 仝，性情温和、智稳插翅虎、义释宋公明、误失小衙内...",
            "天孤星 花和尚－鲁智深，嫉恶如仇，脾气火爆，粗中有细，拳打镇关西、大闹五台山、倒拔垂杨柳、大闹野猪林、大闹桃花村",
            "天伤星 行 者－武 松，武艺高强，崇尚忠义，景阳冈打虎，醉打蒋门神、威镇安平寨、大闹飞云浦、夜走蜈蚣岭、醉打孔亮",
            "天立星 双枪将－董 平，勇猛无敌，知恩图报",
            "天捷星 没羽箭－张 清，善用飞石打人作战英勇，飞石打英雄、缘配琼英",
            "天暗星 青面兽－杨 志，精明能干、粗暴蛮横  汴京城卖刀、北京斗武、押送金银担",
            "双天佑星 金枪手－徐 宁，会使倒铁钩，帮助宋江打破连环马、教使钩镰枪",
            "天空星 急先锋－索 超，性格急躁，东郭争功",
            "天速星 神行太保－戴 宗，行走如飞、智取公孙胜、定计出乐和 ",
            "天异星 赤发鬼－刘 唐，爱结识好汉，性格暴躁 醉卧凌官殿、放火烧战船 ",
            "天杀星 黑旋风－李 逵，正直粗鲁，勇猛无比，杀李鬼、斗浪里白条、沂岭杀四虎、打死殷天锡、斧劈罗真人、探穴救柴进、元宵闹东京...",
            "天微星 九纹龙－史 进，重义气，性格直爽，机智勇猛，野走华阴县、剪径赤松林",
            "天究星 没遮拦－穆 弘，性格暴躁，粗鲁",
            "天退星 插翅虎－雷 横， 脾气暴躁，为人耿直、枷打白秀英",
            "天寿星 混江龙－李 俊，为人正直，水中功夫超强",
            "天剑星 立地太岁－阮小二，武艺出众，英勇善战",
            "天平星 船火儿－张 横，投靠梁山，英勇善战，大闹浔阳江",
            "天罪星 短命二郎－阮小五，水中好汉，奋勇杀敌",
            "天损星 浪里白条－张 顺，水中功夫好，豪爽仗义，惩恶济善，有仇必报，活捉黄炳文、夜闹金沙渡、凿漏海鳅船、夜伏金山寺、魂捉方天定",
            "天败星 活阎罗－阮小七， 心快口快、倒船偷御酒",
            "天牢星 病关索－杨 雄，为人正直，醉骂潘巧云、大闹翠屏山",
            "天慧星 拚命三郎－石 秀，好打抱不平，智杀裴如海，火烧祝家店 ",
            "天暴星 两头蛇－解 珍，作战英勇",
            "天哭星 双尾蝎－解 宝，为人灵活，作战英勇",
            "天巧星 浪子－燕 青，武功高强，为人风流、智扑擎天柱、月夜遇道君、秋林渡射雁",
            "地魁星 神机军师－朱 武，精通阵法，广有谋略、打破六花阵",
            "地煞星 镇三山－黄 信，一身好武艺，英勇善战，大闹青州道",
            "地勇星 病尉迟－孙 立，精熟弓马，武艺过人，正直",
            "地杰星 丑郡马－宣 赞,相貌丑陋，武艺出众",
            "地雄星 井木犴－郝思文，仗义侠胆，有勇有谋",
            "地威星 百胜将－韩 滔，力大无穷，有勇有谋",
            "地英星 天目将－彭 玘， 扶危救困，义气第一",
            "地奇星 圣水将－单廷珪,风流潇洒，气宇轩昂",
            "地猛星 神火将－魏定国，风流潇洒，礼貌待人",
            "地文星 圣手书生－萧 让，擅长写字，不爱说话",
            "地正星 铁面孔目－裴 宣，忍辱负重，忠诚憨厚",
            "地阔星 摩云金翅－欧 鹏,武功不低，挫折感强，比较谨慎",
            "地阖星 火眼狻猊－邓 飞，武功不差，舍己为人",
            "地强星 锦毛虎－燕 顺",
            "地暗星 锦豹子－杨 林，很聪明，比较谨慎",
            "地轴星 轰天雷－凌 振",
            "地会星 神算子－蒋 敬，武力高强，归顺梁山",
            "地佐星 小温侯－吕 方",
            "地佑星 赛仁贵－郭 盛，义气为重",
            "地灵星 神 医－安道全,医术高明，好色",
            "地兽星 紫髯伯－皇甫端，医道高明，诊治马病，手到病除",
            "地微星 矮脚虎－王 英，五短身材，一双光眼，嗜色如命",
            "地慧星 一丈青－扈三娘，武功高强，郁郁寡欢",
            "地暴星 丧门神－鲍 旭，正直粗鲁，勇猛无比",
            "地然星 混世魔王－樊 瑞，阴柔有余、阳刚不足",
            "地猖星 毛头星－孔 明，武艺不精，比较讲义气",
            "地狂星 独火星－孔 亮，本事低微，武功很差",
            "地飞星 八臂那吒－项 充",
            "地走星 飞天大圣－李 衮",
            "地巧星 玉臂匠－金大坚，技法纯熟，雕刻栩栩如生",
            "地明星 铁笛仙－马 麟，提前踏入社会混帮派，好勇斗狠",
            "地进星 出洞蛟－童 威，能伏水，会驾船",
            "地退星 翻江蜃－童 猛，水性极好",
            "地满星 玉幡竿－孟 康，人高马大，善于制造大小船只",
            "地遂星 通臂猿－侯 健，飞针走线，技艺高超",
            "地周星 跳涧虎－陈 达，体魄强健,生性粗鲁",
            "地隐星 白花蛇－杨 春，使一口大杆刀，武艺精熟",
            "地异星 白面郎君－郑天寿，鲁莽，比较重义气",
            "地理星 九尾龟－陶宗旺，力大无比，正直勇敢",
            "地俊星 铁扇子－宋 清，没什么武功，性格内向",
            "地乐星 铁叫子－乐 和，聪明伶俐，各种乐曲，一学便会",
            "地捷星 花项虎－龚 旺，会使飞枪，正直勇敢",
            "地速星 中箭虎－丁得孙，会使飞叉，正直勇敢",
            "地镇星 小遮拦－穆 春，当地一霸，四处惹是生非",
            "地稽星 操刀鬼－曹 正",
            "地魔星 云里金刚－宋 万，高大威猛，武艺平常",
            "地妖星 摸着天－杜 迁，本事平平，武艺一般",
            "地幽星 病大虫－薛 永，身手不错，会使枪棒",
            "地伏星 金眼彪－施 恩，使得一身好拳棒，会施展恩惠 义夺快活林，三入死囚牢、重霸孟州道",
            "地空星 小霸王－周 通，精于算计，毫无义气 醉入销金帐",
            "地僻星 打虎将－李 忠，虚伪，吝啬",
            "地全星 鬼脸儿－杜 兴，性刚烈，知恩图报，有情有义",
            "地孤星 金钱豹子－汤 隆，善于打造兵器，有绝技在身、赚徐宁上山",
            "地短星 出林龙－邹 渊，性起高强，不肯容人",
            "地角星 独角龙－邹 润，为人慷慨忠良，有一身好武艺",
            "地囚星 旱地忽律－朱 贵，心地善良，性格直率，水亭施号箭",
            "地藏星 笑面虎－朱 富，为人和善，心思缜密，机智多谋",
            "地平星 铁臂膊－蔡 福，贪婪，而又慈悲",
            "地损星 一枝花－蔡 庆，不得罪人，精明，圆滑",
            "地察星 青眼虎－李 云，有一身好本事，为人仗义",
            "地奴星 催命判官－李 立",
            "地恶星 没面目－焦 挺，拳脚熟练，讲义气",
            "地丑星 石将军－石 勇，武功一般，粗蛮胆大",
            "地数星 小尉迟－孙 新，正直勇敢，讲义气",
            "地阴星 母大虫－顾大嫂，豪爽急躁，倔强暴躁",
            "地刑星 菜园子－张 青",
            "地壮星 母夜叉－孙二娘，野蛮，杀人成性，英明豪放，孟州卖人肉",
            "地劣星 活闪婆－王定六，没什么本事，身材瘦小，有一身好腿脚",
            "地健星 险道神－郁保四，为人正直，仗义勇猛",
            "地耗星 白日鼠－白 胜，胆大但不能吃苦",
            "地贼星 鼓上蚤－时 迁，身轻似燕，爱偷东西、火烧翠云楼",
            "地狗星 金毛犬－段景住,武功不好，只会逃跑，告状"
    };

}
